### ISSUE TITLE
Qin: service-level is commented out

### ISSUE THREAD

**Issue by alreadytiredofnomcom** [alreadytiredofnomcom/L2SMissues#20]
We have a container called 'service-level'
leaf cos-identifier
leaf color-identifier
leaf ingress-bw-profile-per-evc
leaf ingress-bw-profile-per-cos-id
leaf egress-bw-profile-per-evc
leaf egress-bw-profile-per-cos-id
leaf byte-offset
leaf COS

It is currently commented out

**Comment by sunseawq** [comment]
Commented out container 'service-level' has been removed.
